const API=(window.BUDGETIQ_API||'http://localhost:8000').replace(/\/$/,'');
const $=id=>document.getElementById(id);const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Math.max(0,Number(x)||0);const today=()=>new Date().toISOString();
const create=()=>({schema:2,organization:'Community Learning Centre',year:new Date().getFullYear()+1,currency:'GHS',ceiling:0,uplift:10,status:'Draft',objectives:[],programmes:[],activities:[],revenues:[],expenses:[],reviews:[]});
let project=create(),projectId=null,version=null,authToken=sessionStorage.getItem('budgetiq-token')||'',saveTimer=null,writeQueue=Promise.resolve();
let active='plan';const money=v=>`${project.currency||'GHS'} ${num(v).toLocaleString('en-GH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const lineTotal=l=>num(l.frequency)*num(l.quantity)*num(l.unitPrice);
const activityTotal=a=>(a.costs||[]).reduce((s,l)=>s+lineTotal(l),0);
const total=()=>project.activities.reduce((s,a)=>s+activityTotal(a),0);
const projected=()=>project.revenues.reduce((s,r)=>s+num(r.projected),0);
const received=()=>project.revenues.reduce((s,r)=>s+num(r.received),0);
const committed=()=>project.expenses.reduce((s,e)=>s+num(e.committed),0);
const paid=()=>project.expenses.reduce((s,e)=>s+num(e.paid),0);
function apiRequest(path,method='GET',data){return fetch(`${API}/api${path}`,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(authToken?{'Authorization':`Bearer ${authToken}`}:{})},body:data?JSON.stringify(data):undefined}).then(async r=>{const value=await r.json().catch(()=>({}));if(!r.ok){const detail=value.detail;const fieldError=Array.isArray(detail)?detail[0]:null;const field=fieldError?.loc?.at(-1);throw Error(typeof detail==='string'?detail:fieldError?`${field==='email'?'Email':field==='password'?'Password':'Input'}: ${fieldError.msg}`:`Request failed (${r.status})`)}return value})}
async function refreshProjects(selectId){const items=await apiRequest('/projects');$('project-picker').innerHTML=items.map(x=>`<option value="${clean(x.id)}" ${x.id===selectId?'selected':''}>${clean(x.name)} · ${x.year}</option>`).join('');if(!items.length){project=create();const created=await apiRequest('/projects','POST',{name:project.organization,year:project.year,document:project});projectId=created.id;version=created.version;return refreshProjects(projectId)}if(!selectId||!items.find(x=>x.id===selectId))selectId=items[0].id;projectId=selectId;const result=await apiRequest(`/projects/${projectId}`);version=result.version;project=result.document;renderAll()}
function save(){if(!authToken||!projectId)return;$('save-indicator').textContent='Saving to server…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{const id=projectId,snapshot=structuredClone(project);writeQueue=writeQueue.then(async()=>{if(id!==projectId)return;const result=await apiRequest(`/projects/${id}`,'PUT',{name:snapshot.organization,year:Number(snapshot.year),document:snapshot,version});version=result.version;$('save-indicator').textContent='Saved on server';refreshPickerLabel()}).catch(err=>{$('save-indicator').textContent='Save failed — export a backup';message(err.message,true)})},700)}
function refreshPickerLabel(){const selected=$('project-picker').selectedOptions[0];if(selected)selected.textContent=`${project.organization} · ${project.year}`}
async function startNewProject(data){await writeQueue;clearTimeout(saveTimer);if(projectId)await apiRequest(`/projects/${projectId}`,'PUT',{name:project.organization,year:Number(project.year),document:project,version}).then(x=>{version=x.version}).catch(err=>message(err.message,true));project=data;const created=await apiRequest('/projects','POST',{name:project.organization,year:Number(project.year),document:project});projectId=created.id;version=created.version;await refreshProjects(projectId)}
async function authenticate(mode){const email=$('auth-email'),password=$('auth-password');if(!email.value.trim()||!email.checkValidity()){$('auth-message').textContent='Enter a valid email address.';email.focus();return}if(password.value.length<12){$('auth-message').textContent='Password must be at least 12 characters.';password.focus();return}$('auth-message').textContent='Connecting…';try{const result=await apiRequest(`/auth/${mode}`,'POST',{email:email.value.trim(),password:password.value});authToken=result.token;sessionStorage.setItem('budgetiq-token',authToken);password.value='';await refreshProjects();$('auth-screen').hidden=true;$('auth-message').textContent=''}catch(err){$('auth-message').textContent=err.message}}
$('auth-form').onsubmit=e=>{e.preventDefault();authenticate('login')};$('register').onclick=()=>authenticate('register');$('sign-out').onclick=async()=>{clearTimeout(saveTimer);await writeQueue;try{if(projectId)await apiRequest(`/projects/${projectId}`,'PUT',{name:project.organization,year:Number(project.year),document:project,version})}catch(err){message('Save failed before sign out. Export a backup and retry.',true);return}authToken='';projectId=null;version=null;sessionStorage.removeItem('budgetiq-token');$('auth-screen').hidden=false;message('Signed out.')};$('project-picker').onchange=async e=>{const selected=e.target.value;clearTimeout(saveTimer);await writeQueue;try{if(projectId){const result=await apiRequest(`/projects/${projectId}`,'PUT',{name:project.organization,year:Number(project.year),document:project,version});version=result.version}await refreshProjects(selected)}catch(err){message(err.message,true)}};

function message(s,error=false){$('message').textContent=s;$('message').className=error?'error':''}
function option(items,selected,placeholder='Unassigned'){return `<option value="">${placeholder}</option>`+items.map(x=>`<option value="${clean(x.id)}" ${x.id===selected?'selected':''}>${clean(x.title)}</option>`).join('')}
function categoryOptions(selected){return ['Transport','Venue','Refreshments','Materials','Allowances','Equipment','Services','Other'].map(x=>`<option ${selected===x?'selected':''}>${x}</option>`).join('')}
function sourceOptions(selected){return ['User entered rate','Prior approved budget','Actual spending','Supplier quote','Planning assumption'].map(x=>`<option ${selected===x?'selected':''}>${x}</option>`).join('')}
function render(){const focus=document.activeElement;if(focus?.matches('input,select,textarea') && focus.dataset.bind)return;renderAll()}
function renderAll(){ $('organization').value=project.organization;$('year').value=project.year;$('currency').value=project.currency;$('ceiling').value=project.ceiling||'';$('uplift').value=project.uplift;$('status-badge').textContent=project.status;$('grand').textContent=money(total());
 $('objectives-list').innerHTML=project.objectives.length?project.objectives.map(o=>`<div class="entity"><div><b>${clean(o.title)}</b><small>${clean(o.target||'Add a measurable target')}</small></div><button data-delete="objective:${clean(o.id)}" aria-label="Remove objective">×</button></div>`).join(''):'<p class="muted">No objectives added yet.</p>';
 $('programme-objective').innerHTML=option(project.objectives,'','Select objective');$('programmes-list').innerHTML=project.programmes.length?project.programmes.map(p=>`<div class="entity"><div><b>${clean(p.title)}</b><small>${clean(project.objectives.find(o=>o.id===p.objectiveId)?.title||'Unassigned objective')}</small></div><button data-delete="programme:${clean(p.id)}" aria-label="Remove programme">×</button></div>`).join(''):'<p class="muted">No programmes added yet.</p>';
 $('activities-list').innerHTML=project.activities.length?project.activities.map(a=>`<div class="activity"><div class="activity-head"><label>Activity<input data-bind="activity:${a.id}:title" value="${clean(a.title)}"></label><label>Programme<select data-bind="activity:${a.id}:programmeId">${option(project.programmes,a.programmeId,'Choose programme')}</select></label><label>Quarter<select data-bind="activity:${a.id}:quarter">${[1,2,3,4].map(q=>`<option value="${q}" ${Number(a.quarter)===q?'selected':''}>Q${q}</option>`).join('')}</select></label><label>Expected result<input data-bind="activity:${a.id}:expectedResult" placeholder="e.g. 100 learners" value="${clean(a.expectedResult||'')}"></label><button class="icon-btn" data-delete="activity:${a.id}" title="Remove activity">×</button></div><div class="activity-meta"><label>Result delivered<input data-bind="activity:${a.id}:actualResult" value="${clean(a.actualResult||'')}"></label><label>Result note<input data-bind="activity:${a.id}:resultNote" value="${clean(a.resultNote||'')}"></label></div><div class="table-wrap"><table class="cost-table"><thead><tr><th>Cost category</th><th>Cost item</th><th>Frequency</th><th>Quantity</th><th>Unit price</th><th>Funding source</th><th>Rate evidence</th><th>Line total</th><th></th></tr></thead><tbody>${(a.costs||[]).map(l=>`<tr><td><select data-bind="cost:${a.id}:${l.id}:category">${categoryOptions(l.category)}</select></td><td><input data-bind="cost:${a.id}:${l.id}:item" value="${clean(l.item)}"></td>${['frequency','quantity','unitPrice'].map(k=>`<td><input type="number" min="0" step="any" data-bind="cost:${a.id}:${l.id}:${k}" value="${num(l[k])}"></td>`).join('')}<td><input data-bind="cost:${a.id}:${l.id}:fundingSource" placeholder="e.g. Grant" value="${clean(l.fundingSource||'')}"></td><td><select data-bind="cost:${a.id}:${l.id}:evidence">${sourceOptions(l.evidence)}</select></td><td class="row-total">${money(lineTotal(l))}</td><td><button class="icon-btn" data-delete="cost:${a.id}:${l.id}" title="Remove cost">×</button></td></tr>`).join('')}</tbody></table></div><div class="activity-foot"><button class="outline" data-add-cost="${a.id}">+ Cost line</button><strong>${money(activityTotal(a))}</strong></div></div>`).join(''):'<p class="muted">Add an activity or import an action plan to begin.</p>';
 const hasCeiling=num(project.ceiling)>0,gap=hasCeiling?Math.max(0,total()-num(project.ceiling)):0;$('funding-summary').innerHTML=`<div class="report-row"><span>Full plan</span><b>${money(total())}</b></div><div class="report-row"><span>Ceiling</span><b>${hasCeiling?money(project.ceiling):'Not set'}</b></div><div class="report-row"><span>Funding gap</span><b>${hasCeiling?money(gap):'Set a ceiling'}</b></div><div class="report-row"><span>Projected sources</span><b>${money(projected())}</b></div><div class="report-row"><span>Received so far</span><b>${money(received())}</b></div>`;
 $('revenues-list').innerHTML=`<table class="data-table"><thead><tr><th>Source</th><th>Type</th><th>Projected</th><th>Received</th><th>Quarter</th><th></th></tr></thead><tbody>${project.revenues.map(r=>`<tr><td><input data-bind="revenue:${r.id}:name" value="${clean(r.name)}"></td><td><select data-bind="revenue:${r.id}:type">${['IGF','Grant','Allocation','Donation','Sales','Other'].map(x=>`<option ${r.type===x?'selected':''}>${x}</option>`).join('')}</select></td>${['projected','received'].map(k=>`<td><input type="number" min="0" step="any" data-bind="revenue:${r.id}:${k}" value="${num(r[k])}"></td>`).join('')}<td><select data-bind="revenue:${r.id}:quarter">${[1,2,3,4].map(q=>`<option value="${q}" ${Number(r.quarter)===q?'selected':''}>Q${q}</option>`).join('')}</select></td><td><button class="icon-btn" data-delete="revenue:${r.id}">×</button></td></tr>`).join('')}</tbody></table>${project.revenues.length?'':'<p class="muted">Add an IGF, grant, allocation or other source.</p>'}`;
 $('expenses-list').innerHTML=`<table class="data-table"><thead><tr><th>Activity</th><th>Description</th><th>Quarter</th><th>Committed</th><th>Paid</th><th></th></tr></thead><tbody>${project.expenses.map(e=>`<tr><td><select data-bind="expense:${e.id}:activityId">${option(project.activities,e.activityId,'Select activity')}</select></td><td><input data-bind="expense:${e.id}:description" value="${clean(e.description||'')}"></td><td><select data-bind="expense:${e.id}:quarter">${[1,2,3,4].map(q=>`<option value="${q}" ${Number(e.quarter)===q?'selected':''}>Q${q}</option>`).join('')}</select></td>${['committed','paid'].map(k=>`<td><input type="number" min="0" step="any" data-bind="expense:${e.id}:${k}" value="${num(e[k])}"></td>`).join('')}<td><button class="icon-btn" data-delete="expense:${e.id}">×</button></td></tr>`).join('')}</tbody></table>${project.expenses.length?'':'<p class="muted">No commitments or payments recorded.</p>'}`;
 $('execution-summary').innerHTML=metric('Plan',money(total()))+metric('Committed',money(committed()))+metric('Paid',money(paid()));
 $('review-list').innerHTML=project.reviews.length?[...project.reviews].reverse().map(r=>`<div class="review-event"><b>${clean(r.decision)}</b> · ${clean(r.name)} (${clean(r.role)})<small>${clean(r.at)} · ${clean(r.comment||'No comment')} · Plan ${money(r.planTotal)}</small></div>`).join(''):'<p class="muted">No decisions recorded yet.</p>';
 const variance=total()-paid();$('metrics').innerHTML=metric('Planned',money(total()))+metric('Paid',money(paid()))+metric('Remaining against plan',money(Math.max(0,variance)),variance<0?'warn':'good')+metric('Received',money(received()))+metric('Funding gap',money(gap),gap?'warn':'good')+metric('Recorded decisions',project.reviews.length);
 const reduced=hasCeiling?Math.min(total(),num(project.ceiling)):0;const higher=project.activities.reduce((s,a)=>s+(a.costs||[]).reduce((v,l)=>v+lineTotal(l)*(1+Number(project.uplift||0)/100),0),0);$('scenario-list').innerHTML=`<div class="report-row"><span>Full plan</span><b>${money(total())}</b></div><div class="report-row"><span>Ceiling constrained · available envelope</span><b>${hasCeiling?money(reduced):'Set a ceiling'}</b></div><div class="report-row"><span>Unfunded part · prioritization needed</span><b>${hasCeiling?money(gap):'—'}</b></div><div class="report-row"><span>Prices ${Number(project.uplift||0)>=0?'+':''}${project.uplift}% · same quantities</span><b>${money(higher)}</b></div><p class="muted">The ceiling scenario shows an envelope; it does not automatically remove activities.</p>`;
 const counts={};project.activities.forEach(a=>(a.costs||[]).forEach(l=>{counts[l.evidence||'Planning assumption']=(counts[l.evidence||'Planning assumption']||0)+1}));$('evidence-list').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="report-row"><span>${clean(k)}</span><b>${v} lines</b></div>`).join('')+'<p class="muted">Past rates and quotes must be verified before approval. No trained AI model is used in this release.</p>';
 $('programme-report').innerHTML=project.programmes.map(p=>{const arr=project.activities.filter(a=>a.programmeId===p.id);return `<div class="report-row"><span>${clean(p.title)} · ${arr.length} activities · ${clean(project.objectives.find(o=>o.id===p.objectiveId)?.title||'No objective')}</span><b>${money(arr.reduce((s,a)=>s+activityTotal(a),0))}</b></div>`}).join('')||'<p class="muted">Link programmes and activities to see their totals.</p>';
 $('quarter-report').innerHTML=[1,2,3,4].map(q=>{const plan=project.activities.filter(a=>Number(a.quarter)===q).reduce((s,a)=>s+activityTotal(a),0),income=project.revenues.filter(r=>Number(r.quarter)===q).reduce((s,r)=>s+num(r.received),0),spent=project.expenses.filter(e=>Number(e.quarter)===q).reduce((s,e)=>s+num(e.paid),0);return `<div class="report-row"><span>Q${q} · plan ${money(plan)} · received ${money(income)}</span><b>paid ${money(spent)}</b></div>`}).join('');
}
function metric(title,value,style=''){return `<div class="metric ${style}"><span>${title}</span><strong>${value}</strong></div>`}
function touch(){if(project.status==='Approved')project.status='Reopened';save();renderAll()}
function addCost(a){a.costs.push({id:uid(),category:'Other',item:'New cost item',frequency:1,quantity:1,unitPrice:0,fundingSource:'',evidence:'Planning assumption'});touch()}
function change(bind,value){const parts=bind.split(':');let obj,key=parts.at(-1);if(parts[0]==='project')obj=project;else if(parts[0]==='activity')obj=project.activities.find(x=>x.id===parts[1]);else if(parts[0]==='cost')obj=project.activities.find(x=>x.id===parts[1])?.costs.find(x=>x.id===parts[2]);else obj=project[parts[0]==='revenue'?'revenues':'expenses'].find(x=>x.id===parts[1]);if(!obj)return;key=parts.at(-1);obj[key]=['year','ceiling','uplift','frequency','quantity','unitPrice','projected','received','committed','paid','quarter'].includes(key)?Number(value)||0:value;if(project.status==='Approved')project.status='Reopened';save();renderAll()}
document.addEventListener('change',e=>{if(e.target.dataset.bind)change(e.target.dataset.bind,e.target.value)});
for(const k of ['organization','year','currency','ceiling','uplift'])$(k).addEventListener('change',e=>change('project:'+k,e.target.value));
document.addEventListener('click',e=>{const del=e.target.closest('[data-delete]');if(del){const [type,id,child]=del.dataset.delete.split(':');if(type==='cost'){const a=project.activities.find(x=>x.id===id);a.costs=a.costs.filter(x=>x.id!==child)}else{const prop={objective:'objectives',programme:'programmes',activity:'activities',revenue:'revenues',expense:'expenses'}[type];project[prop]=project[prop].filter(x=>x.id!==id)}touch()}const c=e.target.closest('[data-add-cost]');if(c){const a=project.activities.find(x=>x.id===c.dataset.addCost);if(a)addCost(a)}});
$('add-objective').onclick=()=>{const title=$('objective-title').value.trim();if(!title)return message('Enter an objective.',true);project.objectives.push({id:uid(),title,target:$('objective-target').value.trim()});$('objective-title').value='';$('objective-target').value='';touch()};
$('add-programme').onclick=()=>{const title=$('programme-title').value.trim();if(!title)return message('Enter a programme.',true);project.programmes.push({id:uid(),title,objectiveId:$('programme-objective').value});$('programme-title').value='';touch()};
$('add-activity').onclick=()=>{const a={id:uid(),title:'New activity',programmeId:project.programmes[0]?.id||'',quarter:1,expectedResult:'',actualResult:'',resultNote:'',costs:[]};project.activities.push(a);addCost(a)};
$('add-revenue').onclick=()=>{project.revenues.push({id:uid(),name:'New funding source',type:'Allocation',projected:0,received:0,quarter:1});touch()};
$('add-expense').onclick=()=>{project.expenses.push({id:uid(),activityId:project.activities[0]?.id||'',description:'New expense',quarter:1,committed:0,paid:0});touch()};
$('record-review').onclick=()=>{const name=$('review-name').value.trim();if(!name)return message('Enter a name for the review log.',true);const decision=$('review-decision').value;project.reviews.push({id:uid(),at:today(),name,role:$('review-role').value,decision,comment:$('review-comment').value.trim(),planTotal:total()});project.status=decision==='Approved'?'Approved':decision==='Reopened'?'Reopened':decision==='Changes requested'?'Changes requested':decision==='Reviewed'?'Reviewed':'Submitted';$('review-comment').value='';save();renderAll();message('Decision saved with this project. Identity beyond the account is not verified.')};
$('new-project').onclick=async()=>{try{await startNewProject(create());message('New server-saved budget created.')}catch(err){message(err.message,true)}};
$('sample-project').onclick=async()=>{const example=create();let o=uid(),p=uid(),a=uid();example.objectives=[{id:o,title:'Expand practical digital skills',target:'Train 120 learners'}];example.programmes=[{id:p,title:'Community technology workshops',objectiveId:o}];example.activities=[{id:a,title:'Weekend computer skills workshops',programmeId:p,quarter:2,expectedResult:'120 learners trained',actualResult:'',resultNote:'',costs:[{id:uid(),category:'Venue',item:'Training room',frequency:4,quantity:1,unitPrice:300,fundingSource:'Grant',evidence:'Planning assumption'},{id:uid(),category:'Materials',item:'Learner materials',frequency:4,quantity:30,unitPrice:20,fundingSource:'Grant',evidence:'Planning assumption'},{id:uid(),category:'Transport',item:'Facilitator travel',frequency:4,quantity:2,unitPrice:100,fundingSource:'IGF',evidence:'Planning assumption'}]}];example.ceiling=4000;example.revenues=[{id:uid(),name:'Community grant',type:'Grant',projected:3500,received:0,quarter:2},{id:uid(),name:'Course fees',type:'IGF',projected:1000,received:0,quarter:2}];try{await startNewProject(example);message('Fictional example saved as a new project. All rates are illustrative.')}catch(err){message(err.message,true)}};
$('next-year').onclick=async()=>{if(!project.expenses.length||paid()===0)return message('Record actual payments before building a next-year reference.',true);if(!confirm('Create a new next-year draft using paid amounts by activity? Export this project first to preserve the current year.'))return;const old=project,next=create();next.organization=old.organization;next.year=Number(old.year)+1;next.currency=old.currency;next.uplift=old.uplift;next.objectives=structuredClone(old.objectives);next.programmes=structuredClone(old.programmes);next.activities=old.activities.map(a=>{let actual=old.expenses.filter(e=>e.activityId===a.id).reduce((s,e)=>s+num(e.paid),0);return {...structuredClone(a),actualResult:'',resultNote:'',costs:[{id:uid(),category:'Other',item:'Prior-year paid total · break into detailed costs',frequency:1,quantity:1,unitPrice:Math.round(actual*(1+Number(old.uplift||0)/100)*100)/100,fundingSource:'',evidence:'Actual spending'}]}});next.revenues=old.revenues.map(r=>({...structuredClone(r),received:0,projected:num(r.received)||num(r.projected)}));try{await startNewProject(next);message(`Draft for ${project.year} created from prior-year paid amounts with ${project.uplift}% price adjustment. Split each estimate into verified cost lines.`)}catch(err){message(err.message,true)}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;document.querySelectorAll('.nav-item,.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===active||x.id===active));$('section-title').textContent={plan:'Plan & cost',fund:'Funding',execute:'Execution',review:'Review',insights:'Insights'}[active];$('section-kicker').textContent={plan:'ANNUAL PLAN',fund:'RESOURCE ENVELOPE',execute:'BUDGET ACTUALS',review:'DECISION RECORD',insights:'BUDGET INTELLIGENCE'}[active]});
async function upload(file,route){const form=new FormData();form.append('file',file);const response=await fetch(`${API}/api/${route}/import`,{method:'POST',body:form});const result=await response.json();if(!response.ok)throw Error(result.detail||'Import failed');return result}
async function handleUpload(file,route){if(!file)return;message('Reading '+file.name+'…');try{const result=await upload(file,route);const items=route==='plan'?result.lines:result.references;for(const item of items){project.activities.push({id:uid(),title:item.activity,programmeId:'',quarter:1,expectedResult:'',actualResult:'',resultNote:'',costs:[{id:uid(),category:'Other',item:route==='plan'?'Activity cost':'Historic activity · enter current cost',frequency:1,quantity:1,unitPrice:0,fundingSource:'',evidence:'Planning assumption'}]})}touch();message(`${items.length} possible activities added. Review titles, detailed costs and rate evidence.`)}catch(err){message(err.message,true)}}
$('plan-upload').onchange=e=>handleUpload(e.target.files[0],'plan');$('history-upload').onchange=e=>handleUpload(e.target.files[0],'history');
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('project-export').onclick=()=>download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),`budgetiq-${project.year}-project.json`);
$('project-import').onchange=async e=>{try{const raw=await e.target.files[0].text(),data=JSON.parse(raw);if(data.schema!==2||!Array.isArray(data.activities)||!Array.isArray(data.revenues)||!Array.isArray(data.expenses)||!Array.isArray(data.objectives)||!Array.isArray(data.programmes)||!Array.isArray(data.reviews))throw Error('Invalid BudgetIQ project file');await startNewProject(data);message('Backup restored as a new server project.')}catch(err){message(err.message,true)}};
function exportPayload(){return {organization:project.organization,year:Number(project.year),currency:project.currency,ceiling:num(project.ceiling),status:project.status,objectives:project.objectives,programmes:project.programmes,activities:project.activities,revenues:project.revenues,expenses:project.expenses,reviews:project.reviews,lines:project.activities.flatMap(a=>a.costs.map(l=>({activity:a.title,category:l.category,cost_item:l.item,frequency:num(l.frequency),people:num(l.quantity),unit_price:num(l.unitPrice),source:l.evidence,note:`Funding: ${l.fundingSource||'Unassigned'}; Q${a.quarter}`})))}}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{if(!project.activities.length)return message('Add an activity before exporting.',true);try{message('Preparing report…');const format=b.dataset.export,res=await fetch(`${API}/api/budget/export/${format}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(exportPayload())});if(!res.ok)throw Error('Export failed: '+res.status);download(await res.blob(),`budgetiq-${project.year}-budget.${format}`);message('Draft downloaded. Verify prices, funding and approvals.')}catch(err){message(err.message,true)}});
renderAll();if(authToken){apiRequest('/auth/me').then(()=>refreshProjects()).then(()=>$('auth-screen').hidden=true).catch(()=>{authToken='';sessionStorage.removeItem('budgetiq-token');$('auth-screen').hidden=false})}
