const API=(window.BUDGETIQ_API||'http://localhost:8000').replace(/\/$/,'');
const $=id=>document.getElementById(id);let lines=[];
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`${($('currency').value||'GHS').toUpperCase()} ${Number(n||0).toLocaleString('en-GH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function render(){const body=$('lines');body.innerHTML=''; $('empty').hidden=!!lines.length;
 lines.forEach((line,i)=>{let tr=document.createElement('tr');tr.innerHTML=`<td><input data-i="${i}" data-key="activity" aria-label="Activity ${i+1}" value="${escapeHTML(line.activity)}"><small>${escapeHTML(line.category||'Other')} · ${escapeHTML(line.source||'Estimate')}</small></td><td><input data-i="${i}" data-key="cost_item" aria-label="Cost item ${i+1}" value="${escapeHTML(line.cost_item||'Activity cost')}"></td>${['frequency','people','unit_price'].map(k=>`<td><input data-i="${i}" data-key="${k}" aria-label="${k} ${i+1}" type="number" min="0" step="any" value="${Number(line[k]||0)}"></td>`).join('')}<td class="row-total">${money(line.frequency*line.people*line.unit_price)}</td><td><button class="remove" data-remove="${i}" aria-label="Remove row ${i+1}">×</button></td>`;body.appendChild(tr)});updateTotal()}
function updateTotal(){[...$('lines').rows].forEach((row,i)=>row.querySelector('.row-total').textContent=money(lines[i].frequency*lines[i].people*lines[i].unit_price));$('grand').textContent=money(lines.reduce((s,l)=>s+l.frequency*l.people*l.unit_price,0))}
$('lines').addEventListener('input',e=>{const {i,key}=e.target.dataset;if(i===undefined)return;lines[Number(i)][key]=['frequency','people','unit_price'].includes(key)?Math.max(0,Number(e.target.value)||0):e.target.value;updateTotal()});
$('lines').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){lines.splice(Number(e.target.dataset.remove),1);render()}});
$('currency').addEventListener('input',updateTotal);
$('add').addEventListener('click',()=>{lines.push({activity:'New activity',category:'Other',cost_item:'Activity cost',frequency:1,people:1,unit_price:0,source:'Manual entry',note:'Verify current rate'});render();$('lines').lastElementChild?.querySelector('input')?.focus()});
function status(message,error=false){$('status').textContent=message;$('status').className=error?'error':'success'}
async function upload(file,route){const form=new FormData();form.append('file',file);const response=await fetch(`${API}/api/${route}/import`,{method:'POST',body:form});const result=await response.json();if(!response.ok)throw Error(result.detail||'Import failed');return result}
$('plan').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;$('plan-name').textContent=f.name;status('Reading action plan…');try{const r=await upload(f,'plan');lines.push(...r.lines);render();status(r.message+(r.lines.length?' Add or split cost items as needed.':' Try a text based file or add items manually.'))}catch(err){status(err.message,true)}});
$('history').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;$('history-name').textContent=f.name;status('Reading previous budget…');try{const r=await upload(f,'history');lines.push(...r.references.map(x=>({...x,source:'Previous budget (review rate)',note:'Historic reference; current rate required'})));render();status(`${r.references.length} historical activity references added. Review duplicates and enter current rates.`)}catch(err){status(err.message,true)}});
document.querySelectorAll('[data-format]').forEach(btn=>btn.addEventListener('click',async()=>{if(!lines.length)return status('Add at least one activity before exporting.',true);try{status('Preparing download…');const payload={organization:$('organization').value||'New organization',year:Number($('year').value),currency:$('currency').value||'GHS',lines};const res=await fetch(`${API}/api/budget/export/${btn.dataset.format}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok){const r=await res.json();throw Error(JSON.stringify(r.detail||r))}const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=`budgetiq-${payload.year}-draft.${btn.dataset.format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Draft downloaded. Confirm costs and approvals before use.')}catch(err){status(err.message,true)}}));
render();
